#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.1

#Obstacle marking parameters
obstacle_range: 6.0
raytrace_range: 6.0
#max_obstacle_height: 2.0

#The footprint of the robot and associated padding
footprint: [[-0.6, -0.37], [-0.6, 0.37], [0.6, 0.37], [0.6, -0.37]]
footprint_padding: 0.2

track_unknown_space: true
always_send_full_costmap: true

#Cost function parameters
inflation_radius: 0.0
#cost_scaling_factor: 10.0

observation_sources: VLP16_lidar_front #VLP16_lidar_back

VLP16_lidar_front:
  sensor_frame: VLP16_lidar_front_base_link_fake
  topic: /VLP16_lidar_front/pointcloud_to_scan
  max_obstacle_height: 10.0
  min_obstacle_height: -0.5
  expected_update_rate: 0.3
  clearing: true
  marking: true
  inf_is_valid: true # required for COSTMAP correct update
#  observation_persistence: 0.5
#  obstacle_range: 6.0
#  raytrace_range: 6.0
  data_type: LaserScan

#VLP16_lidar_back:
#  sensor_frame: VLP16_lidar_back_base_link
#  topic: /VLP16_lidar_back/pointcloud_to_scan
#  max_obstacle_height: 10.0
#  min_obstacle_height: -0.5
#  expected_update_rate: 0.3
#  clearing: true
#  marking: true
#  inf_is_valid: true # required for COSTMAP correct update
##  observation_persistence: 0.5
##  obstacle_range: 6.0
##  raytrace_range: 6.0
#  data_type: LaserScan

#bosch_uss5_rr_sag:
#  topics: ['/bosch_uss5/ultrasound_rr_sag', ] #'/bosch_uss5/ultrasound_rr_lat'
#  clear_threshold: 0.5
#  mark_threshold: 0.9
#  clear_on_max_reading: true
#  no_readings_timeout: 2.0
#
#plugins:
#  - {name: bosch_uss5_rr_sag, type: "range_sensor_layer::RangeSensorLayer"}
