#local_costmap:

  #Set the global and robot frames for the costmap
global_frame: base_link
robot_base_frame: base_link

#Set the update and publish frequency of the costmap
update_frequency: 30.0
publish_frequency: 30.0
#  transform_tolerance: 0.5

# costmap to be a rolling window centered at the robot
static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.01
#origin_x: 0.0
#origin_y: 0.0